name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Run UT
      run: docker run -it --volume .:/var/work/GasStationPro --entrypoint /var/work/GasStationPro/GasTeminal/gas_station/UnitTests/build_run_ut.sh  t-azs
